version: "3"

services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "6000:6000"

  go-app:
    build:
      context: ./go-app
    ports:
      - "8080:8080"

  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000"
